

export const WRITE_RECORD_ID = 'WRITE_RECORD_ID'
export const WRITE_ELEMENTS_TO_DELETE = 'WRITE_ELEMENTS_TO_DELETE'
export const WRITE_TABLE_MESSAGE = 'WRITE_TABLE_MESSAGE'


export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const TOGGLE_FETCH_LOADER = 'TOGGLE_FETCH_LOADER'
export const TOGGLE_PAGE_LOADER = 'TOGGLE_PAGE_LOADER'
export const WRITE_AUTH_MESSAGE = 'WRITE_AUTH_MESSAGE'


export const WRITE_CATEGORIES = 'WRITE_CATEGORIES'
export const WRITE_CATEGORY_BY_ID = 'WRITE_CATEGORY_BY_ID'
export const TOGGLE_AUTH ='TOGGLE_AUTH'


export const WRITE_PRODUCTS = 'WRITE_PRODUCTS'
export const WRITE_PRODUCT_BY_ID = 'WRITE_PRODUCT_BY_ID'


export const WRITE_PROVIDER_BY_ID = 'WRITE_PROVIDER_BY_ID'
export const WRITE_PROVIDER = 'WRITE_PROVIDER'

export const WRITE_USERS = 'WRITE_USERS'
export const WRITE_USER_BY_ID = 'WRITE_USER_BY_ID'

export const WRITE_ORDERS = 'WRITE_ORDERS'
export const WRITE_ORDER_BY_ID = 'WRITE_ORDER_BY_ID'