

export const WRITE_RECORD_ID = 'WRITE_RECORD_ID'
export const WRITE_ELEMENTS_TO_DELETE = 'WRITE_ELEMENTS_TO_DELETE'
export const WRITE_TABLE_MESSAGE = 'WRITE_TABLE_MESSAGE'
export const SEARCHING='SEARCHING'

export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const TOGGLE_FETCH_LOADER = 'TOGGLE_FETCH_LOADER'
export const TOGGLE_PAGE_LOADER = 'TOGGLE_PAGE_LOADER'
export const WRITE_AUTH_MESSAGE = 'WRITE_AUTH_MESSAGE'
export const WRITE_USERNAME = 'WRITE_USERNAME'
export const WRITE_USER_ID = 'WRITE_USER_ID'



export const WRITE_CATEGORIES = 'WRITE_CATEGORIES'
export const WRITE_CATEGORY_BY_ID = 'WRITE_CATEGORY_BY_ID'
export const DELETED_CATEGORY = 'DELETED_CATEGORY'
export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES'
export const CATEGORY_TOGGLE_FETCH_LOADER = 'CATEGORY_TOGGLE_FETCH_LOADER'



export const TOGGLE_AUTH ='TOGGLE_AUTH'
export const TOGGLE_NOTIFICATION ='TOGGLE_NOTIFICATION'


export const WRITE_PRODUCTS = 'WRITE_PRODUCTS'
export const WRITE_PRODUCT_BY_ID = 'WRITE_PRODUCT_BY_ID'
export const WRITE_RAITING_BY_ID = 'WRITE_RAITING_BY_ID'
export const ADDED_PRODUCT = 'ADDED_PRODUCT'
export const DELETED_PRODUCT = 'DELETED_PRODUCT'
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS'
export const WRITE_MEASURE_UNITS='WRITE_MEASURE_UNITS'
export const PRODUCT_TOGGLE_FETCH_LOADER='PRODUCT_TOGGLE_FETCH_LOADER'


export const WRITE_PROVIDER_BY_ID = 'WRITE_PROVIDER_BY_ID'
export const WRITE_PROVIDER = 'WRITE_PROVIDER'
export const WRITE_ACTIVE_PROVIDERS = 'WRITE_ACTIVE_PROVIDERS'
export const DELETED_PROVIDER = 'DELETED_PROVIDER'
export const PROVIDER_TOGGLE_FETCH_LOADER = 'PROVIDER_TOGGLE_FETCH_LOADER'
export const CLEAR_PROVIDERS = 'CLEAR_PROVIDERS'


export const WRITE_USERS = 'WRITE_USERS'
export const WRITE_USER_BY_ID = 'WRITE_USER_BY_ID'
export const DELETED_USER = 'DELETED_USER'
export const USER_TOGGLE_FETCH_LOADER = 'USER_TOGGLE_FETCH_LOADER'
export const CLEAR_USERS = 'CLEAR_USERS'


export const WRITE_ORDERS = 'WRITE_ORDERS'
export const WRITE_ORDER_BY_ID = 'WRITE_ORDER_BY_ID'
export const DELETED_ORDER = 'DELETED_ORDER'
export const CLEAR_ORDERS = 'CLEAR_ORDERS'
export const ORDER_TOGGLE_FETCH_LOADER = 'ORDER_TOGGLE_FETCH_LOADER'


export const WRITE_DELIVERY_CASH = 'WRITE_DELIVERY_CASH'


export const WRITE_FAQ = 'WRITE_FAQ'
export const WRITE_FAQ_BY_ID = 'WRITE_FAQ_BY_ID'
export const DELETED_FAQ = 'DELETED_FAQ'
export const CLEAR_FAQ = 'CLEAR_FAQ'
export const FAQ_TOGGLE_FETCH_LOADER = 'FAQ_TOGGLE_FETCH_LOADER'


export const  WRITE_ABOUT_US = 'WRITE_ABOUT_US'
export const  WRITE_ABOUT_US_BY_ID = 'WRITE_ABOUT_US_BY_ID'
export const  DELETED_ABOUT_US = 'DELETED_ABOUT_US'
export const CLEAR_ABOUT_US = 'CLEAR_ABOUT_US'
export const  ABOUT_TOGGLE_FETCH_LOADER = 'ABOUT_TOGGLE_FETCH_LOADER'