

export const WRITE_RECORD_ID = 'WRITE_RECORD_ID'
export const WRITE_ELEMENTS_TO_DELETE = 'WRITE_ELEMENTS_TO_DELETE'


export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const TOGGLE_FETCH_LOADER = 'TOGGLE_FETCH_LOADER'
export const WRITE_CATEGORIES = 'WRITE_CATEGORIES'
export const WRITE_CATEGORY_BY_ID = 'WRITE_CATEGORY_BY_ID'
export const TOGGLE_AUTH ='TOGGLE_AUTH'


export const WRITE_PRODUCTS = 'WRITE_PRODUCTS'
export const WRITE_PRODUCT_BY_ID = 'WRITE_PRODUCT_BY_ID'


export const WRITE_PROVIDER_BY_ID = 'WRITE_PROVIDER_BY_ID'
export const WRITE_PROVIDER = 'WRITE_PROVIDER'